### PR TITLE
Solve warnings.marcomaggi 2018 10 30

### PR DESCRIPTION
**Pull request by marcomaggi**
Fix warning raised by gcc when the new warning flags are used.

### CODE REVIEW

**Comment by hartwork** [comment]
I have merged 627dc65fefd49d0164ef8f866eb79719d2a51a52 to master now. For 06ad3f8a33f66a7bc595aed869aca8cf325886cb I'm unsure about why we'd need volatile here. Happy to cherry-pick than one later if it turns out needed.

Sorry it took me so long to review these changes. Thanks for contributing to Expat!

**Comment by marcomaggi** [comment]
The use of `volatile` makes GCC shut up when the `-Wclobbered` option is used.  There is a `longjmp` call in `minicheck.c`; althoug I am not sure if/where it is used.  But GCC complains.

**Comment by hartwork** [comment]
@marcomaggi with my GCC 8.2.0 and `-Wextra` which includes `-Wclobbered` accroding to `man gcc`, I do not get that warning. Which version of GCC is yours?

**Comment by marcomaggi** [comment]
@hartwork Right now I'm using GCC 9.1.0.  I do not remember what I was using at the time I worked on that branch.  If I check out the `solve-warnings` branch in my not-updated repository, and I remove the `volatile` keywords, I get this:

```
gcc -DHAVE_CONFIG_H -I. -I../../tests -I..  -I../../tests/../lib -DHAVE_EXPAT_CONFIG_H  -O3 -Wall -Wextra -fexceptions -fno-strict-aliasing -Wmissing-prototypes -Wstrict-prototypes -pedantic -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wrestrict -Wnull-dereference -Wjump-misses-init -Wdouble-promotion -Wshadow -Wformat=2 -Wmisleading-indentation -fvisibility=hidden -DXML_ENABLE_VISIBILITY=1 -MT minicheck.o -MD -MP -MF .deps/minicheck.Tpo -c -o minicheck.o ../../tests/minicheck.c
../../tests/minicheck.c: In function 'srunner_run_all':
../../tests/minicheck.c:168:13: warning: variable 'tc' might be clobbered by 'longjmp' or 'vfork' [-Wclobbered]
  168 |     TCase * tc;
      |             ^~
../../tests/minicheck.c:173:13: warning: variable 'i' might be clobbered by 'longjmp' or 'vfork' [-Wclobbered]
  173 |         int i;
      |             ^
```

maybe the code has changed in a more recent revision.

**Comment by hartwork** [comment]
I wasn't able to reproduce the warnings with GCC 9.1.0 myself but MinGW GCC 4.8.2 showed that and your patch addressed the warning. I have cherry-picked it to b306ee963f543df7a519108ca8e6875e06e58be3 on `master` now.

**Pull request closed without merging**
