### PR TITLE
Fix source comment typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S ./testdata,./expat/Changes`

### CODE REVIEW

**Comment by hartwork** [comment]
Looks great — thank you!

**Comment by RMJ10** [comment]
Actually when talking about string termination, "nul-terminated" is correct and "null-terminated" is a little dubious.  The ASCII character 0x00 is 'NUL' not 'NULL'.

**Comment by hartwork** [comment]
Hi Rhodri, I checked

- https://en.wikipedia.org/wiki/Null_character and
- https://www.compart.com/en/unicode/U+0000#UNC_DB and
- ftp://ftp.unicode.org/Public/UNIDATA/UnicodeData.txt

and I am not sure if null is better or more right than nul. The last two indicate that NUL was used "formerly" so they speak in favor of NULL. What do you think?

**Comment by RMJ10** [comment]
I prefer NUL, to keep it distinct from the "invalid pointer" NULL.  That said, it doesn't matter a lot and both options communicate what is intended, I just dislike having perfectly valid technical English "corrected".

**Comment by hartwork** [comment]
> [..] I just dislike having perfectly valid technical English "corrected".

I get your point.

**Comment by luzpaz** [comment]
> I prefer NUL, to keep it distinct from the "invalid pointer" NULL. That said, it doesn't matter a lot and both options communicate what is intended, I just dislike having perfectly valid technical English "corrected".

I will revise the auxiliary dictionary i used for `codespell` to avoid this in the future. sorry for any frustration this may have caused

**Pull request merged**
