### PR TITLE
Run SINGLE_BYTES with no chunking, too

### PR DESCRIPTION
**Pull request by Snild-Sony**
...including one test that needed fixing to get it passing in these new conditions.

### CODE REVIEW

**Comment by Snild-Sony** [comment]
Note: this PR also contains the commits from https://github.com/libexpat/libexpat/pull/757 -- maybe it'd be a good idea to review and merge that one first. Then the diff of this PR will shrink a little. Or we can just do this one big merge, if you prefer. Either way is fine by me.

**Comment by Snild-Sony** [comment]
I'm kind of stumped about the CI error here. It's a parse error in handlers.c:485. I haven't seen that locally, and many other checks succeeded here. Maybe the specific defines in that task (looks like `-DEXPAT_CONTEXT_BYTES=OFF`?) uncovers a problem I haven't seen.

I'll keep digging.

**Comment by Snild-Sony** [comment]
Yes, running `./configure enable_xml_context=no` allowed me to reproduce.

It looks like the syntax error is returned from `processInternalEntity()` -- which is only called in the chunksize==0 case.

```
(gdb) info b
Num     Type           Disp Enb Address            What
2       breakpoint     keep y   0x000055555555cd4f in test_alloc_nested_entities at alloc_tests.c:1624
	breakpoint already hit 6 times
        enable 3
        p g_chunkSize
        cont
3       breakpoint     keep n   0x000055555558b04d in processInternalEntity at xmlparse.c:5717
	breakpoint already hit 1 time
        disable 3
5       breakpoint     keep y   0x000055555555ce21 in test_alloc_nested_entities at alloc_tests.c:1659
	breakpoint already hit 5 times
        disable 3
        cont
(gdb) r
Starting program: /home/snild/repos/libexpat/expat/tests/runtests 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Expat version: expat_2.5.0

Breakpoint 2, test_alloc_nested_entities () at alloc_tests.c:1624
1624	START_TEST(test_alloc_nested_entities) {
$73 = 0

Breakpoint 3, processInternalEntity (parser=0x5555555e55a0, entity=0x5555555e30b0, betweenDecl=1 '\001') at xmlparse.c:5717
5717	processInternalEntity(XML_Parser parser, ENTITY *entity, XML_Bool betweenDecl) {
(gdb) finish
Run till exit from #0  processInternalEntity (parser=0x5555555e55a0, entity=0x5555555e30b0, betweenDecl=1 '\001')
    at xmlparse.c:5717
0x000055555558a382 in doProlog (parser=0x5555555e55a0, enc=0x5555555db360 <utf8_encoding>, s=0x5555555afcb3 "%pe2;", end=0x5555555afcb8 "", tok=28, next=0x5555555afcb8 "", nextPtr=0x7fffffffd890, haveMore=0 '\000', allowClosingDoctype=1 '\001', account=XML_ACCOUNT_DIRECT) at xmlparse.c:5432
5432	          result = processInternalEntity(parser, entity, betweenDecl);
Value returned is $74 = XML_ERROR_SYNTAX
(gdb) cont
Continuing.
ERROR:     2: syntax error (line 3, offset 0)
    reported from handlers.c, line 485
FAIL [chunksize=0]: test_alloc_nested_entities (during actual test at handlers.c:485)

Breakpoint 2, test_alloc_nested_entities () at alloc_tests.c:1624
1624	START_TEST(test_alloc_nested_entities) {
$75 = 1

Breakpoint 5, test_alloc_nested_entities () at alloc_tests.c:1659
1659	END_TEST

Breakpoint 2, test_alloc_nested_entities () at alloc_tests.c:1624
1624	START_TEST(test_alloc_nested_entities) {
$76 = 2

Breakpoint 5, test_alloc_nested_entities () at alloc_tests.c:1659
1659	END_TEST

Breakpoint 2, test_alloc_nested_entities () at alloc_tests.c:1624
1624	START_TEST(test_alloc_nested_entities) {
$77 = 3

Breakpoint 5, test_alloc_nested_entities () at alloc_tests.c:1659
1659	END_TEST

Breakpoint 2, test_alloc_nested_entities () at alloc_tests.c:1624
1624	START_TEST(test_alloc_nested_entities) {
$78 = 4

Breakpoint 5, test_alloc_nested_entities () at alloc_tests.c:1659
1659	END_TEST

Breakpoint 2, test_alloc_nested_entities () at alloc_tests.c:1624
1624	START_TEST(test_alloc_nested_entities) {
$79 = 5

Breakpoint 5, test_alloc_nested_entities () at alloc_tests.c:1659
1659	END_TEST
99%: Checks: 2076, Failed: 1
[Inferior 1 (process 1565658) exited with code 01]
```

My assumption is that previously, parsing has just not gotten far enough to hit the syntax error before the test's allocation limit is hit. Running without chunking probably reduces the allocation count a bit, as does running without context bytes -- together resulting in getting just far enough to hit the syntax error.

To support my hypothesis, increasing `g_allocation_count` a lot makes all chunk sizes fail in the same way:

```
:expat$ git diff
diff --git a/expat/tests/alloc_tests.c b/expat/tests/alloc_tests.c
index 40d0d121..cb5a22a9 100644
--- a/expat/tests/alloc_tests.c
+++ b/expat/tests/alloc_tests.c
@@ -1649,7 +1649,7 @@ START_TEST(test_alloc_nested_entities) {
          "Memory Fail not faulted", NULL, XML_ERROR_NO_MEMORY};
 
   /* Causes an allocation error in a nested storeEntityValue() */
-  g_allocation_count = 12;
+  g_allocation_count = 1200000;
   XML_SetUserData(g_parser, &test_data);
   XML_SetParamEntityParsing(g_parser, XML_PARAM_ENTITY_PARSING_ALWAYS);
   XML_SetExternalEntityRefHandler(g_parser, external_entity_faulter);

:expat$ ./configure # note: "enable_xml_context=no" is NOT set here.
[...]
:expat$ make clean
[...]
:expat$ make -j10 check
[...]
FAIL: runtests_cxx
FAIL: runtests
============================================================================
Testsuite summary for expat 2.5.0
============================================================================
# TOTAL: 2
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
Please report to expat-bugs@libexpat.org
============================================================================
[...]
:expat$ cat tests/test-suite.log 
=======================================
   expat 2.5.0: tests/test-suite.log
=======================================

# TOTAL: 2
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: runtests
==============

ERROR:     2: syntax error (line 3, offset 0)
    reported from handlers.c, line 485
ERROR:     2: syntax error (line 3, offset 0)
    reported from handlers.c, line 485
ERROR:     2: syntax error (line 3, offset 0)
    reported from handlers.c, line 485
ERROR:     2: syntax error (line 3, offset 0)
    reported from handlers.c, line 485
ERROR:     2: syntax error (line 3, offset 0)
    reported from handlers.c, line 485
ERROR:     2: syntax error (line 3, offset 0)
    reported from handlers.c, line 485
Expat version: expat_2.5.0
FAIL [chunksize=0]: test_alloc_nested_entities (during actual test at handlers.c:485)
FAIL [chunksize=1]: test_alloc_nested_entities (during actual test at handlers.c:485)
FAIL [chunksize=2]: test_alloc_nested_entities (during actual test at handlers.c:485)
FAIL [chunksize=3]: test_alloc_nested_entities (during actual test at handlers.c:485)
FAIL [chunksize=4]: test_alloc_nested_entities (during actual test at handlers.c:485)
FAIL [chunksize=5]: test_alloc_nested_entities (during actual test at handlers.c:485)
99%: Checks: 2082, Failed: 6
FAIL runtests (exit status: 1)

FAIL: runtests_cxx
==================

ERROR:     2: syntax error (line 3, offset 0)
    reported from handlers.c, line 485
ERROR:     2: syntax error (line 3, offset 0)
    reported from handlers.c, line 485
ERROR:     2: syntax error (line 3, offset 0)
    reported from handlers.c, line 485
ERROR:     2: syntax error (line 3, offset 0)
    reported from handlers.c, line 485
ERROR:     2: syntax error (line 3, offset 0)
    reported from handlers.c, line 485
ERROR:     2: syntax error (line 3, offset 0)
    reported from handlers.c, line 485
Expat version: expat_2.5.0
FAIL [chunksize=0]: test_alloc_nested_entities (during actual test at handlers.c:485)
FAIL [chunksize=1]: test_alloc_nested_entities (during actual test at handlers.c:485)
FAIL [chunksize=2]: test_alloc_nested_entities (during actual test at handlers.c:485)
FAIL [chunksize=3]: test_alloc_nested_entities (during actual test at handlers.c:485)
FAIL [chunksize=4]: test_alloc_nested_entities (during actual test at handlers.c:485)
FAIL [chunksize=5]: test_alloc_nested_entities (during actual test at handlers.c:485)
99%: Checks: 2082, Failed: 6
FAIL runtests_cxx (exit status: 1)
```

Now I just need to figure out if it's a real syntax error in the test data, or a bug in the parser...

**Comment by Snild-Sony** [comment]
I think it's a real syntax error.

This solves it:

```
:expat$ git diff -U20
diff --git a/expat/tests/alloc_tests.c b/expat/tests/alloc_tests.c
index 40d0d121..de90f183 100644
--- a/expat/tests/alloc_tests.c
+++ b/expat/tests/alloc_tests.c
@@ -1628,41 +1628,41 @@ START_TEST(test_alloc_nested_entities) {
       = {"<!ENTITY % pe1 '"
          /* 64 characters per line */
          "ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP"
          "ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP"
          "ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP"
          "ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP"
          "ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP"
          "ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP"
          "ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP"
          "ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP"
          "ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP"
          "ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP"
          "ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP"
          "ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP"
          "ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP"
          "ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP"
          "ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP"
          "ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP"
          "'>\n"
          "<!ENTITY % pe2 '%pe1;'>\n"
-         "%pe2;",
+         "<!ENTITY % pe3 '%pe2;'>",
          "Memory Fail not faulted", NULL, XML_ERROR_NO_MEMORY};
 
   /* Causes an allocation error in a nested storeEntityValue() */
   g_allocation_count = 12;
   XML_SetUserData(g_parser, &test_data);
   XML_SetParamEntityParsing(g_parser, XML_PARAM_ENTITY_PARSING_ALWAYS);
   XML_SetExternalEntityRefHandler(g_parser, external_entity_faulter);
   expect_failure(text, XML_ERROR_EXTERNAL_ENTITY_HANDLING,
                  "Entity allocation failure not noted");
 }
 END_TEST
```

After expansion, the old content would have a plain "ABCDEF...". That's not valid, right?

**Comment by Snild-Sony** [comment]
Added new commit "tests: Replace invalid entity expansion in test_alloc_nested_entities" to solve the issue. @hartwork, please check that I've not completely misdiagnosed it. :)

**Review by hartwork — APPROVED** [review]
@Snild-Sony great to have this fixed, thanks! :+1:

**Pull request merged**
