### PR TITLE
Fix fallthrough related warnings

### PR DESCRIPTION
**Pull request by antmak**
Some warnings appear in gcc 7+

-Wimplicit-fallthrough
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

### CODE REVIEW

**Comment by hartwork** [comment]
I like the direction, thanks for your contribution to Expat!

The addition if this line
```
__attribute__ ((fallthrough)); /* gcc doesn't parse the 'fall through' hint properly because there are ifdef-s */
```
is a problem because we have no guarantee that the compiler is GCC (e.g. it could be MSVC) and also [that line causes failure on Travis](https://travis-ci.org/libexpat/libexpat/jobs/400140383#L956).

Would making an empty macro like
```
#define FALLTHROUGH
```
and use like
```
     case BT_NMSTRT:
       if (!(BYTE_TO_ASCII(enc, ptr) & ~0x7f))
         break;
       FALLTHROUGH
```
be able to satisfy `-Wimplicit-fallthrough[=3]`? If it works outside of macros, maybe a two-step macro could work inside macros?

**Comment by antmak** [comment]
Somethins like that works

```
#if (__GNUC__ >= 7)
#define     FALLTHROUGH __attribute__ ((fallthrough));
#else
#define     FALLTHROUGH
#endif

int main()
{
    int s = 1;
    
    switch (s) {
        case 2:
            s = 2;
#if B
            break;
#else            
            s = 4;
            FALLTHROUGH
#endif
        case 3:   
            s = 3;
    }
}
```
What do you think, can we replace all `/* fall through */` hints to `FALLTHROUGH`, or use it in only one place?

**Comment by antmak** [comment]
Hmm, by the gcc's bugzilla https://gcc.gnu.org/bugzilla/show_bug.cgi?id=77817#c17 I think we can use the comment after #endif 
```
...
        if (!parser->m_declEntity)
          return XML_ERROR_NO_MEMORY;
        parser->m_declEntity->publicId = NULL;
      }
#endif /* XML_DTD */
    /* fall through */
    case XML_ROLE_ENTITY_SYSTEM_ID:
...
```

**Comment by hartwork** [comment]
Cool, thank you!

**Pull request merged**
