### PR TITLE
Add missing #define in expat_config.h

### PR DESCRIPTION
**Pull request by iology**
Missing #define: XML_LARGE_SIZE, XML_UNICODE, XML_UNICODE_WCHAR_T

Fix configure.ac according to README.md, hopefully not breaking any old
projects. Also fix CMakeLists.txt regarding issue #330.

### CODE REVIEW

**Comment by RMJ10** [comment]
IIRC defining XML_UNICODE_WCHAR_T is a big mistake.  wchar_t is not the same size on Linux and Windows, and on one of them (Linux I think) that breaks Expat's internal storage badly.

**Review by hartwork — CHANGES_REQUESTED** [review]
Hi @iology,

we cannot move `XML_UNICODE` and/or `XML_UNICODE_WCHAR_T` into `expat_config.h` because a single shared `expat_config.h` is used for both `libexpat.so` and `libexpatw.so` (wuth `w`) [in Debian](https://packages.debian.org/sid/amd64/libexpat1-dev/filelist). So we'll need a strong reason to break backwards compatibility with changes like that. What is your motivation for this change?

Best, Sebastian

**Comment by iology** [comment]
@hartwork I didn't know there is libexpatw which shares the same header file (instead of `expatw_config.h`).

Understood, so now only `XML_LARGE_SIZE` is included in the header. Branch rebased.

**Comment by iology** [comment]
ah, silly me... maybe someone will compile libexpat.so with -DXML_LARGE_SIZE and libexpatw.so without it, so `#define XML_LARGE_SIZE` should be guarded by `#ifndef XML_LARGE_SIZE`. Is it good to include this guard after `#define XML_LARGE_SIZE` (may be commented out) in `expat_config.h` (also for package distribution)? The same could be done for XML_UNICODE and XML_UNICODE_WCHAR_T?

**Comment by iology** [comment]
similar problem in `lib/pkgconfig/expat.pc` (always w/o "w") built using cmake: `Libs: -L${libdir} -lexpat (w/ or w/o "w")`

The ncurses library does the right thing: ncurses++.pc ncurses++w.pc ncurses.pc ncursesw.pc

Since the cmake build is experimental, it's no problem if we have both expat_config.h and expatw_config.h for libexpact.* and libexpactw.* and thus it's okay to include the #define of XML_LARGE_SIZE, XML_UNICODE and XML_UNICODE_WCHAR_T in expat_config.h and/or expatw_config.h?

**Comment by iology** [comment]
I update the patch with no change to `configure.ac`:

    CMake: Separate config files for libexpat.* & libexpatw.*
    
    libexpat.* : expat.pc expat_config.h cmake/expat-<version>
    libexpatw.* : expatw.pc expatw_config.h cmake/expatw-<version>
    
    Also add missing #define for XML_LARGE_SIZE, XML_UNICODE and
    XML_UNICODE_WCHAR_T in expat_config.h & expatw_config.h
    
    To find the wide-char version of expat using cmake, now do:
        find_package(expat [..] CONFIG [..] NAMES expatw)
    
    These changes only affect the installation of expat.

Now the installation looks like:

    libexpat
    ├── bin
    │   └── xmlwf
    ├── include
    │   ├── expat.h
    │   ├── expat_config.h
    │   ├── expat_external.h
    │   └── expatw_config.h
    └── lib
        ├── cmake
        │   ├── expat-2.2.9
        │   │   ├── expat-noconfig.cmake
        │   │   └── expat.cmake
        │   └── expatw-2.2.9
        │       ├── expat-noconfig.cmake
        │       └── expat.cmake
        ├── libexpat.1.6.11.dylib
        ├── libexpat.1.dylib -> libexpat.1.6.11.dylib
        ├── libexpat.a
        ├── libexpat.dylib -> libexpat.1.dylib
        ├── libexpatw.1.6.11.dylib
        ├── libexpatw.1.dylib -> libexpatw.1.6.11.dylib
        ├── libexpatw.a
        ├── libexpatw.dylib -> libexpatw.1.dylib
        └── pkgconfig
            ├── expat.pc
            └── expatw.pc

**Comment by hartwork** [comment]
Hi @iology,

we cannot rename `expat_config.h` to `expatw_config.h` while the code includes verbatim `expat_config.h`. The CI is not green, you have not answered my question what your motivation for this pull request is. If there's a bug you want to fix, please open a new issue, then we agree on an option to fix, and then someone builds a pull request. I'm happy to team up with you but this pull request is on the wrong track. Let's start fresh, with bug reports and high level requirements. Thank you.

**Comment by iology** [comment]
@hartwork

> you have not answered my question what your motivation for this pull request is

The configuration was not easy to get right when I'm not compiling libexpat every time a new project is set up, that is, I'm not going to always explicitly include the compile flags `-DXML_*`.  I just compile libexpat once and simply include `expat_config.h` (or `expatw_config.h`) from the installation directory.

It seems one thing that we need to fix is `pkgconfig/expat.pc` but I don't know what's people's workaround to get linker flag `-lexpatw` for `libexpatw.so` if pkg-config returns `-lexpat`.

I'll change this pull request's title later so people can find this discussion more easily.

**Pull request closed without merging**
