### PR TITLE
Prepare release 2.4.9 (part of #642)

### PR DESCRIPTION
**Pull request by hartwork**
Part of #642

### CODE REVIEW

**Comment by shak5009** [comment]
Thanks for all the efforts on releasing 2.4.9. Is there an estimated date for the R_2_4_9?

**Comment by hartwork** [comment]
@shak5009 I'm expecting just a few days more, maximum.

**Comment by hartwork** [comment]
@shak5009 FYI Expat 2.4.9 has been released earlier today.

**Comment by shak5009** [comment]
> 

Thanks a lot. Really appreciate the efforts.

**Pull request merged**
