### PR TITLE
Get 'make check' to build for XML_UNICODE_WCHAR_T on mingw32

### PR DESCRIPTION
**Pull request by RMJ10**
Basically this is a lot of commits to add appropriate macros to get the coverage tests running with `XML_UNICODE_WCHAR_T` defined using `mingw32` (or Windows, though I haven't verified that).

### CODE REVIEW

**Comment by hartwork** [comment]
I haven't checked the code/commits yet but fed it to the compiler for a start. There are some issues left that still need to be addressed:
```console
# ./configure CFLAGS='-Wall -Wextra -std=c99 -pedantic' CXXFLAGS='-Wall -Wextra -std=c++98 -pedantic' CPPFLAGS=-DXML_UNICODE_WCHAR_T --host=i686-w64-mingw32 --disable-shared && make clean && make -C lib && make check
[..]
make[3]: Entering directory '[..]/expat/tests'
i686-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I..  -I./../lib -DXML_UNICODE_WCHAR_T -DHAVE_EXPAT_CONFIG_H  -Wall -Wextra -std=c99 -pedantic -Wall -Wmissing-prototypes -Wstrict-prototypes -fexceptions -fno-strict-aliasing -MT runtests.o -MD -MP -MF .deps/runtests.Tpo -c -o runtests.o runtests.c
runtests.c: In function ‘test_default_doctype_handler’:
runtests.c:7043:13: warning: initialization from incompatible pointer type
             "'pubname'",
             ^
runtests.c:7043:13: warning: (near initialization for ‘test_data[0].expected’)
runtests.c:7048:13: warning: initialization from incompatible pointer type
             "'test.dtd'",
             ^
runtests.c:7048:13: warning: (near initialization for ‘test_data[1].expected’)
runtests.c: In function ‘test_ns_extremely_long_prefix’:
runtests.c:7688:9: warning: string length ‘4129’ is greater than the length ‘4095’ ISO C99 compilers are required to support [-Woverlength-strings]
         "</doc>";
         ^
runtests.c: In function ‘test_nsalloc_long_namespace’:
runtests.c:11168:9: warning: string length ‘5177’ is greater than the length ‘4095’ ISO C99 compilers are required to support [-Woverlength-strings]
         ":e>";
         ^
runtests.c: In function ‘test_nsalloc_realloc_long_context_in_dtd’:
runtests.c:11725:9: warning: string length ‘4193’ is greater than the length ‘4095’ ISO C99 compilers are required to support [-Woverlength-strings]
         ":doc>";
         ^
mv -f .deps/runtests.Tpo .deps/runtests.Po
/bin/sh ../libtool  --tag=CC   --mode=link i686-w64-mingw32-gcc  -Wall -Wextra -std=c99 -pedantic -Wall -Wmissing-prototypes -Wstrict-prototypes -fexceptions -fno-strict-aliasing  -fno-strict-aliasing -o runtests.exe runtests.o libruntests.a ../lib/libexpat.la 
libtool: link: i686-w64-mingw32-gcc -Wall -Wextra -std=c99 -pedantic -Wall -Wmissing-prototypes -Wstrict-prototypes -fexceptions -fno-strict-aliasing -fno-strict-aliasing -o runtests.exe runtests.o  libruntests.a ../lib/.libs/libexpat.a
i686-w64-mingw32-g++ -DHAVE_CONFIG_H -I. -I..  -I./../lib -DXML_UNICODE_WCHAR_T -DHAVE_EXPAT_CONFIG_H  -Wall -Wextra -std=c++98 -pedantic -fno-strict-aliasing -MT runtestspp.o -MD -MP -MF .deps/runtestspp.Tpo -c -o runtestspp.o runtestspp.cpp
In file included from runtestspp.cpp:36:0:
runtests.c: In function ‘void test_default_doctype_handler()’:
runtests.c:7053:5: error: cannot convert ‘const char*’ to ‘const XML_Char* {aka const wchar_t*}’ in initialization
     };
     ^
runtests.c:7053:5: error: cannot convert ‘const char*’ to ‘const XML_Char* {aka const wchar_t*}’ in initialization
make[3]: *** [Makefile:734: runtestspp.o] Error 1
make[3]: Leaving directory '[..]/expat/tests'
[..]
```

**Comment by hartwork** [comment]
PS: The incompatible pointer type errors seem to be from/when rebasing to `master`.

**Comment by RMJ10** [comment]
I've fixed up the incompatible pointers and split the over-long string literals.  The latter shouldn't affect the tests, since almost all of them feed the data in character by character anyway.

**Comment by hartwork** [comment]
Merged as 227280db70df0388ca828cca1e382c2334731edb now, thanks a lot!

The AppVeyor/Windows issue was b1ef760e0e99e0684b123557a178aded6a524546, if you're curious.

**Pull request closed without merging**
