### PR TITLE
CMake: Render .def file from a template to fix linking (fixes #512) + apply .def file with MinGW

### LINKED ISSUE #512: libexpat.def : error LNK2001: unresolved external symbol XML_SetBillionLaughsAttackProtectionActivationThreshold
Hello,

Starting from v2.4.0, when compiling libexpat under **Windows** using **CMake** and set(EXPAT_DTD OFF), compilation fails with linkage error:
`libexpat.def : error LNK2001: unresolved external symbol XML_SetBillionLaughsAttackProtectionActivationThreshold`

It can be solved by deletion function names from libexpat(w).def.

Regards, Oleh

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #512, related to #611

@neheb @oleg-krasnov @Tieske review and/or testing would be greatly appreciated! :pray:

### CODE REVIEW

**Review by neheb — APPROVED** [review]

**Review by Tieske — APPROVED** [review]
Lgtm only wondering if a similar change is necessary for the attribute info stuff, since that also changes symbol visibility iirc. But that could also be another PR.

**Comment by hartwork** [comment]
> Lgtm only wondering if a similar change is necessary for the attribute info stuff, since that also changes symbol visibility iirc. But that could also be another PR.

@Tieske thanks for having a look! Did you see the attribute info bits that are already included? What more would be needed on that aspect in your opinion?

**Comment by Tieske** [comment]
Sorry, on mobile so hard to check. My thinking was; there were 2 directives, the dtd one and the attribute one, that changed symbol visibility. 

This pr ensure the def file follows the directive as well for the dtd part. Hence  my comment on the attribute one. 

If this was already taken care of, then apologies for the noise

**Comment by hartwork** [comment]
@neheb thanks for the review! :+1:

**Pull request merged**
