### PR TITLE
Fix docbook

### PR DESCRIPTION
**Pull request by stephengroat**
#153

### CODE REVIEW

**Comment by hartwork** [comment]
Thanks for working on this topic!

Please excuse my braindump posting style:

* I remember only now that docbook2x-man and docbook2man are two different tools, not different names for the same thing.  [Former does not seem to support `-o DIRECTORY`](http://manpages.ubuntu.com/manpages/trusty/man1/docbook2x-man.1.html), [latter seems to do](https://linux.die.net/man/1/docbook2man).
  The fact that docbook2x-man does not support that option is the core reason why we even have `doc.mk`.  The related packages in Debian are:
  * [docbook2x](https://packages.debian.org/stretch/amd64/docbook2x/filelist)
  * docbook2man of [docbook-utils](https://packages.debian.org/stretch/all/docbook-utils/filelist)
* [`make distcheck` now fails](https://travis-ci.org/libexpat/libexpat/jobs/283241127)
* Change of indetation with call to `add_custom_comman` with CMake, please revert that bit
* `AC_CHECK_PROGS`
  * If we fail with command missing, we should provide a `--disable-doc` guard to support building without that dependency
  * Please add single spaces after commas
* One of the commits seems to have broken author/committer info

Best, Sebastian

**Comment by stephengroat** [comment]
this should be working and ready for review

**Comment by hartwork** [comment]
I went through the latest version again in depth and have a few more comments:

* Let's drop or change the `DOCBOOK_TO_MAN=` line to support testing and overriding like `./configure DOCBOOK_TO_MAN=/bin/true`. (For CMake I found `cmake -DBUILD_doc=ON -DDOCBOOK_TO_MAN=/bin/true .` to work). Maybe also `AC_ARG_VAR` for `DOCBOOK_TO_MAN` on top would be cool to have to document that in `./configure --help` output.
* If `--with/without-docbook` keeps defaulting to `check`, we should document both `--with-docbook` (enforce) and `--without-docbook` (disable check).
* For `${DOCBOOK_TO_MAN} $<` and `$(RM) ${dist_man_MANS}` please use round braces everywhere, not curly ones, for (style and) consistency
* Also for `$(RM) ${dist_man_MANS}`, please use `$(RM) xmlwf.1` as we don't want to delete "all man pages that are shipped", but "all man pages we built"; I'm aware that could be seen as picky, but the semantics seem wrong to me currently. Please feel free to introduce a new variable instead, if you like.
* We need protection to not ever run `make dist` without putting compiled xmlwf.1 in, unnoticed; maybe the `WITH_DOCBOOK` conditional scope should be made as narrow as possible for a fix so that it would fail loudly then? Maybe embracing the `xmlwf.1` only?  I would love to use something like `AM_DISTCHECK_CONFIGURE_FLAGS` for `make dist` instead, but I'm not aware of such a thing.
* (Optional: CMake is still building the man page in `PROJECT_SOURCE_DIR` rather than `PROJECT_BUILD_DIR`. It's not an issue of the upcoming changes, but a fix would still be welcome, if you want to investigate a clean approach.)

Thanks for your patience!

**Comment by hartwork** [comment]
What do you think?

**Comment by hartwork** [comment]
I have incorporated the review feedback above as extra commits on top now myself. Closing as merged.

**Pull request closed without merging**
