### PR TITLE
[rfc] xmlwf: Drop COM code

### PR DESCRIPTION
**Pull request by hartwork**
@kwaclaw @freddrake are you aware of any reasons that would make us still need this code?

### CODE REVIEW

**Comment by kwaclaw** [comment]
I was not aware it even existed. I assume that some Windows applications
using it might break if it is removed.

**Comment by hartwork** [comment]
Interestingly, the code is linked into xmlwf, not expat.dll. And it's Windows only. I believe if we drop it from 2.2.7 and it turns out needed, we can easily start a new dedicated repo at https://github.com/libexpat with that code alone as a new Windows-only project. It does not use internal Expat symbols but plain public Expat API. What do you think?

**Comment by hartwork** [comment]
Any concerns from @Alex-PLACET @barry-scott @bnason-nf @BlazesRus @DgINC @ennioVisco  @KangLin @pedro-vicente @pepone @ruizpauker @sdroege @snikulov @tbeu @vadz @vanklompf @vslavik @vstinner @vszakats @xantares ?

Thank you!

**Comment by tbeu** [comment]
> I was not aware it even existed.

True here, too.

**Comment by xantares** [comment]
nope!

**Comment by pepone** [comment]
Fine with me, we don't use that code for [zeroc-ice/ice](https://github.com/zeroc-ice/ice)

**Comment by barry-scott** [comment]
I'm not sure why I was asked to comment. Did I comment on this matter in the past? Maybe another barry scott?

**Comment by hartwork** [comment]
> I'm not sure why I was asked to comment. Did I comment on this matter in the past? Maybe another barry scott?

@barry-scott it was because of your past issue report #180 that showed that you use libexpat in context of Windows.

**Comment by hartwork** [comment]
Thanks for the replies so far!

**Comment by vstinner** [comment]
Hi, Python uses libexpat, but it doesn't use xmlwf nor COM.

**Pull request merged**
