### PR TITLE
CMake: Support variable BUILD_SHARED_LIBS (fixes #471)

### LINKED ISSUE #471: BUILD_SHARED_LIBS is not supported (was: Rename EXPAT_SHARED_LIBS to BUILD_SHARED_LIBS)
Hi.
Can you replace your own variable EXPAT_SHARED_LIBS by CMake’s documented BUILD_SHARED_LIBS?
It would ease a little bit maintainers’ life.
Thank you.

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #471

@concatime @1480c1 would this work for you?

### CODE REVIEW

**Comment by 1480c1** [comment]
Seems good to me

**Comment by hartwork** [comment]
@concatime good to merge?

**Comment by concatime** [comment]
Yes, thank you!

**Comment by hartwork** [comment]
Excellent, thanks to the two of you! :pray:

**Pull request merged**
