### PR TITLE
tests: Require a C++11 compiler

### PR DESCRIPTION
**Pull request by hartwork**

### CODE REVIEW

**Comment by hartwork** [comment]
Hi @PolynomialDivision I have not not, no. `./configure CXX='ccache g++'` works fine with GCC 12.3.1 over here. If it matters, please open a new issue about it with more details allowing reproduction in practice and we can go investigate further from there. Thanks!

**Comment by hartwork** [comment]
@PolynomialDivision any news?

**Comment by PolynomialDivision** [comment]
We disabled the tests:
https://github.com/openwrt/openwrt/commit/f3cbdaec29253eafdd4bea75c1af73fc6230853e

**Comment by hartwork** [comment]
@PolynomialDivision is there any interest in getting them re-enabled? If yes please open a new issue with enough details for me to reproduce on Linux. I have ccache 4.9.1 installed and ready waiting for that report.

**Pull request merged**
