### PR TITLE
Fix typos and add ICPSR full name

### PR DESCRIPTION
**Pull request by tbeu**

### CODE REVIEW

**Comment by hartwork** [comment]
Hi!

I am not familiar with the material in that file so my review is only based on observations:
* `accesss` seems to be a new typo.
* The places adding `Political and Social Research` may need something like `, Ann Arbor, MI 48106, December 1991.` more, if http://www-personal.umich.edu/~wmebane/fall96/anes92/nes92pt2.cbk.j is about the same thing.

**Comment by tbeu** [comment]
I updated the PR to fix the `accesss` typo.

**Comment by tbeu** [comment]
Edit: I updated the PR to reflect both review comments.

**Comment by hartwork** [comment]
Merged as-is now, thanks for your contribution!

**Pull request merged**
