### PR TITLE
Include expat_config.h as early as possible

### PR DESCRIPTION
**Pull request by corona10**
closes: https://github.com/libexpat/libexpat/issues/513

### CODE REVIEW

**Comment by corona10** [comment]
@hartwork Please let me know if this is not what you intended :)

**Comment by hartwork** [comment]
@catenacyber PS: The move of `NDEBUG` in `runtests.c` seems missing. `expat_config.h` cannot have the last word on `NDEBUG` for that file.

**Comment by corona10** [comment]
@hartwork Updated PTAL :)

**Comment by hartwork** [comment]
Merged, thanks for your contribution :pray:

**Pull request merged**
