### PR TITLE
Fix INTERFACE_INCLUDE_DIRECTORIES on Haiku

### PR DESCRIPTION
**Pull request by korli**
Not sure if the IMPORTED_LOCATION shouldn't be develop/lib Patch from François Revol.

### CODE REVIEW

**Comment by hartwork** [comment]
Hi @korli, could you please provide a detailed bug report? What is it exactly that this pull request is trying to fix?

**Comment by mmuman** [comment]
IIRC I was trying to port a dependency of OpenSCAD (OpenColorIO possibly), but it failed to find headers, because it searched at the wrong location when configuring with CMake.

Haiku doesn't use `include/` but `headers/`, as a subdirectory of  `/system/develop/`. Moreover, since we consider GCC2 and the newer GCCs as separate archs, depending which compiler is used we might need to use `headers/x86/` instead. So the default unixish behavior doesn't work for us.

As for IMPORTED_LOCATION, I'm not sure because while runtime libs are in `/system/lib`, we are supposed to actually link applications with libs in `/system/develop/lib[/x86]` so I believe we should probably use this.

**Review by hartwork — CHANGES_REQUESTED** [review]
@korli @mmuman thanks for elaborating!

This is indeed likely to be #501 except on a non-Linux platform.
#501 is currently assumed unfeasable to be fixed in a way that works for everyone and so the unfortuante realitiy on that topic is that patching the CMake files installed by Expat Autotools will the way to go for Linux distros with non-standard path.  Now Haiku is not Linux so we could technically add these files to be just right for Haiku.  If we did that (1) we will not be able to detect or prevent breakage upstream because the CI does not cover Haiku and (2) the diff to `cmake/autotools/expat-noconfig__linux.cmake.in` should be minimal, which it does not yet seem to be, e.g. re-applying `INTERFACE_LINK_LIBRARIES "m"` does not seem to be needed (as it's already in `cmake/autotools/expat.cmake`) and avoiding `LIBDIR_BASENAME` would be worth a double check and a related comment and so on.

While I'm the first to aim for a zero-downstream-patches approach on most other cases:  How bad would it be for you to patch `cmake/autotools/expat-noconfig__linux.cmake.in` in Haiku Packaging instead? Maybe it needs nothing more than adding an additional `get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)` line and already work. Here's the two things that Debian keeps patching on the same topic:
- https://sources.debian.org/patches/expat/2.6.0-1/fix-expat-cmake.patch/
- https://sources.debian.org/patches/expat/2.6.0-1/fix-expat-noconfig.patch/

What do you think?

**Comment by hartwork** [comment]
@korli @mmuman what do you think?

**Comment by korli** [comment]
> @korli @mmuman what do you think?

I'm inclined to maintain the current patch as is.

**Comment by hartwork** [comment]
> > @korli @mmuman what do you think?
> 
> I'm inclined to maintain the current patch as is.

@korli to be sure I understand: by that you mean keeping https://github.com/haikuports/haikuports/blob/master/dev-libs/expat/patches/expat-2.6.0.patchset downstream and closing this pull request?

**Comment by korli** [comment]
> @korli to be sure I understand: by that you mean keeping https://github.com/haikuports/haikuports/blob/master/dev-libs/expat/patches/expat-2.6.0.patchset downstream and closing this pull request?

Yes, the current patch can stay until the next release.

**Comment by hartwork** [comment]
> > @korli to be sure I understand: by that you mean keeping https://github.com/haikuports/haikuports/blob/master/dev-libs/expat/patches/expat-2.6.0.patchset downstream and closing this pull request?
> 
> Yes, the current patch can stay until the next release.

@korli thanks for confirming :+1: 

@mmuman how do you feel about [things](https://github.com/libexpat/libexpat/pull/816#pullrequestreview-1870630707)?

**Comment by hartwork** [comment]
> > > @korli to be sure I understand: by that you mean keeping https://github.com/haikuports/haikuports/blob/master/dev-libs/expat/patches/expat-2.6.0.patchset downstream and closing this pull request?
> > 
> > 
> > Yes, the current patch can stay until the next release.
> 
> @korli thanks for confirming 👍
> 
> @mmuman how do you feel about [things](https://github.com/libexpat/libexpat/pull/816#pullrequestreview-1870630707)?

@mmuman do you have a minute?

**Comment by mmuman** [comment]
Sorry I'm still recovering from FOSDEM :sweat_smile: 

Ok to keep it in HaikuPorts for now, at least until the other points are solved. I don't know if you're intending to deprecate autotools or not ?

Ideally we'd have a recipe for git HEAD and build it from time to time, but I don't think we have anything like that set up already.

As for libm, we actually don't even need it as it's included in libroot, and we have a stub for things wanting to link to it, so that can be removed…

**Comment by hartwork** [comment]
> Sorry I'm still recovering from FOSDEM 😅

@mmuman thanks for your reply, I hope FOSDEM wasn't as bad as this makes it sound :wink:

> I don't know if you're intending to deprecate autotools or not ?

So far the then-fully-cyclic dependency Expat -> CMake -> Expat has prevented me from doing that: https://github.com/Kitware/CMake/tree/master/Utilities/cmexpat .

> Ok to keep it in HaikuPorts for now, at least until the other points are solved.

Good, I will close this pull request for good then. Thanks for the discussion!

**Comment by mmuman** [comment]
> @mmuman thanks for your reply, I hope FOSDEM wasn't as bad as this makes it sound 😉

It was great, it's probably more the covid from 2 weeks before actually that's to blame.

**Pull request closed without merging**
