### PR TITLE
CMake: Be less rejective towards unsupported MSVC compilers for Conan (#454)

### LINKED ISSUE #454: [2.3.0] Why CMakeLists prevents to use Visual Studio 2013 & 2015?
@hartwork expat 2.3.0 seems to be perfectly valid for Visual Studio 2015 maybe even 2013, I can understand you don't want to test Visual Studio < 2017, but is there any reason to force an error in CMakeLists?

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #454
Related to #422, #426, #447

Review welcome, thanks in advance! :pray: 

CC @tbeu @SpaceIm

### CODE REVIEW

**Review by tbeu — COMMENTED** [review]
I would not like to see such a big fat screaming warning. If it compiles, it is good enough for me.

Btw, I modified expat 2.3.0 in my environment to work again with VS2010 yesterday. It is just the one include of <stdbool.h> which prevents successful compilation in VS2010.

I'd actually would prefer to revert dd26478455ca91c13e40eed6b26f10dd7efc33fc again. Did not know that the required version was increased after my commit a86a16e2c59183cc39a1123fdd973e283eaf6e91.

**Comment by hartwork** [comment]
> I would not like to see such a big fat screaming warning.

Are you talking about the exclamation marks? To make something visable in a long log where you want people to take action, I think that bit of uppercase is totally fine, it could be a lot louder. It's in Expat interest to have all users on a supported compiler, right?

**Comment by tbeu** [comment]
Well, it is matter of taste.

**Comment by hartwork** [comment]
@tbeu if I dropped the bar of exclamation marks — would that make a difference to you?

**Comment by tbeu** [comment]
Sure, if there is less noise, I would appreciate it.

**Comment by hartwork** [comment]
> Sure, if there is less noise, I would appreciate it.

Done.

**Comment by hartwork** [comment]
@SpaceIm good to merge?

**Review by SpaceIm — APPROVED** [review]
LGTM 👍

**Comment by hartwork** [comment]
Cool, thank you!

**Pull request merged**
