### PR TITLE
Misc. typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3`

### CODE REVIEW

**Comment by hartwork** [comment]
Thanks!

**Comment by luzpaz** [comment]
@hartwork np. BTW, i found dozens of typos in ./testdata/largefiles/wordnet_glossary-20010201.rdf do you want them ? I didn't think you would.. but just letting you know

**Comment by hartwork** [comment]
PS: I can see at https://github.com/libexpat/libexpat/network that you forked at a time where I did experiments with Travis CI to fix it for Expat. Please feel free to the `travis-ci-*` branches you forked as well. I deleted them over here in the meantime.

**Comment by hartwork** [comment]
> @hartwork np. BTW, i found dozens of typos in ./testdata/largefiles/wordnet_glossary-20010201.rdf do you want them ? I didn't think you would.. but just letting you know

Its just test data copied from somewhere years ago. Personally, I think it would be a waste of time to investigate typos there.

**Pull request merged**
